services:
  ghost:
    build: .
    restart: always
    ports:
      - "2368:2368"
    environment:
      url: https://${RAILWAY_PUBLIC_DOMAIN}
      database__client: mysql
      database__connection__host: ${MYSQLHOST}
      database__connection__port: ${MYSQLPORT}
      database__connection__user: ${MYSQLUSER}
      database__connection__password: ${MYSQLPASSWORD}
      database__connection__database: ${MYSQLDATABASE}
      NODE_ENV: production
    volumes:
      - ghost-content:/var/lib/ghost/content

volumes:
  ghost-content:
